# This is a basic workflow to help you get started with Actions

name: Auto Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
          node-version: '13.x'
    - name: Install Dependencies
      run: |
        yarn global add serverless 
        yarn
        sh setup.sh
      env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
    - name: Run local server
      run: |
        yarn db_start &
        yarn local &
    - name: Run test
      run: yarn test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
          node-version: '13.x'
    - name: Install Dependencies
      run: |
        yarn global add serverless 
        yarn

    - name: Deploy to lambda
      run: yarn deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
